#!/usr/bin/env bash
#
# Interactive repo-root .env for Docker production install.
#
set -euo pipefail

_install_env_log() { echo "[NetlifyHub] $*"; }

_install_env_default_origin() {
  local host="localhost"
  if _command_exists curl; then
    local ip
    ip="$(curl -fsS --max-time 2 https://api.ipify.org 2>/dev/null || true)"
    if [[ -n "$ip" ]]; then
      host="$ip"
    fi
  fi
  echo "http://${host}:3000"
}

_generate_token_encryption_key() {
  if _command_exists openssl; then
    openssl rand -hex 24
    return
  fi
  head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 48
}

_escape_for_double_quoted_env() {
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//\$/\\\$}
  printf '%s' "$s"
}

# Writes ${NETLIFYHUB_INSTALL_ROOT}/.env (or prompts to keep existing).
netlifyhub_prompt_env() {
  local root="${NETLIFYHUB_INSTALL_ROOT:-$(pwd)}"
  local env_file="${root}/.env"

  if [[ -f "$env_file" && "${NETLIFYHUB_RECONFIGURE_ENV:-}" != "1" ]]; then
    _install_env_log "Using existing .env (set NETLIFYHUB_RECONFIGURE_ENV=1 to reconfigure)."
    return 0
  fi

  local default_origin admin_user admin_pass token_key cookie_secure vite_title
  default_origin="$(_install_env_default_origin)"
  admin_user="admin"
  admin_pass=""
  token_key="$(_generate_token_encryption_key)"
  cookie_secure="false"
  vite_title="NetlifyHub"

  echo ""
  echo "=== NetlifyHub setup (Docker) ==="
  echo "Press Enter to accept [bracketed] defaults."
  echo ""

  read -rp "Panel URL users will open (WEB_ORIGIN) [${default_origin}]: " _in
  if [[ -n "${_in// }" ]]; then
    default_origin="${_in// /}"
  fi

  if [[ "$default_origin" == https://* ]]; then
    cookie_secure="true"
  fi

  read -rp "Admin username [${admin_user}]: " _in
  if [[ -n "${_in// }" ]]; then
    admin_user="${_in// /}"
  fi

  while [[ -z "$admin_pass" ]]; do
    read -rsp "Admin password (min 8 characters): " admin_pass
    echo ""
    if [[ "${#admin_pass}" -lt 8 ]]; then
      _install_env_log "Password must be at least 8 characters."
      admin_pass=""
    fi
  done

  read -rsp "Confirm admin password: " _in
  echo ""
  if [[ "$_in" != "$admin_pass" ]]; then
    _install_env_log "Passwords do not match."
    exit 1
  fi

  read -rp "App title [${vite_title}]: " _in
  if [[ -n "${_in// }" ]]; then
    vite_title="${_in// /}"
  fi

  local esc_pass
  esc_pass="$(_escape_for_double_quoted_env "$admin_pass")"

  cat >"$env_file" <<EOF
# Generated by NetlifyHub installer (Docker)
WEB_ORIGIN=${default_origin}
VITE_APP_TITLE=${vite_title}
SESSION_TTL_DAYS=7
TOKEN_ENCRYPTION_KEY=${token_key}
TELEGRAM_QUOTA_CRON_PATTERN="0 * * * *"
LOG_LEVEL=info
COOKIE_SECURE=${cookie_secure}

# First admin (created on first API start when database is empty)
SEED_ADMIN_USERNAME=${admin_user}
SEED_ADMIN_PASSWORD="${esc_pass}"
EOF

  chmod 600 "$env_file" 2>/dev/null || true
  _install_env_log "Wrote ${env_file}"
  _install_env_log "WEB_ORIGIN=${default_origin}"
}
